name: Deploy Bicep
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Container tag
        required: true
        default: v1
jobs:
  deploy-bicep:
    env:
      CONTAINER_TAG: ":${{ github.event.inputs.tag == '' && 'v1' || github.event.inputs.tag }}"
      ACR_HOST: "ghcr.io/opsdojo"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/bicep-install@v1
      with:
        version: latest
    - name: Upsert modules
      run: |
        for file in ./bicep-modules/**/*.bicep; do
          [ -f "$file" ] || continue
          module="${file/%\.bicep/${{ env.CONTAINER_TAG }}}"
          echo "$file --> br:${{ env.ACR_HOST }}/${module:2}"
          az bicep publish -f "$file" -t "br:${{ env.ACR_HOST }}/${module:2}" --force
        done